services:
  mysql:
    image: mysql:8.0
    container_name: event-pipeline-mysql
    env_file:
      - ./.env

    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql-init:
    image: mysql:8.0
    depends_on:
      mysql:
        condition: service_healthy
    command: | 
      mysql -h mysql -uroot -ptestpass eventdb -e "
      CREATE TABLE IF NOT EXISTS processed_events (
          id VARCHAR(36) PRIMARY KEY,
          type ENUM('user_action', 'sensor_data', 'system_log') NOT NULL,
          source VARCHAR(50) NOT NULL,
          user_id VARCHAR(50),
          processed_data JSON,
          processing_time_ms INT,
          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
          processed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

          INDEX idx_type_created (type, created_at),
          INDEX idx_user_created (user_id, created_at)
      );"
    restart: "no"
  
  event-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-pipeline
    depends_on:
      - mysql